AY2021S1-CS2103T-T10-3/tp

- src/main/java/chopchop/logic/commands/AddIngredientCommand.java
- src/main/java/chopchop/model/Model.java
- src/main/java/chopchop/model/ModelManager.java
- src/main/java/chopchop/model/attributes/units/Count.java
- src/main/java/chopchop/model/attributes/units/Mass.java
- src/main/java/chopchop/model/attributes/units/Volume.java
- src/main/java/chopchop/model/exceptions/IncompatibleIngredientsException.java
- src/main/java/chopchop/model/ingredient/Ingredient.java
- src/main/java/chopchop/model/ingredient/UniqueIngredientList.java
- src/test/java/chopchop/logic/commands/AddIngredientCommandTest.java
- src/test/java/chopchop/model/ModelStub.java
- src/test/java/chopchop/model/attributes/QuantityTest.java
Half of the work required for #58
> Implement ingredient combining with the `add` command

- src/main/java/chopchop/ui/PinBox.java
- src/main/resources/view/CommandBox2.fxml
- src/main/resources/view/PinBox.fxml
- src/main/resources/view/RecipeDisplay.fxml
- src/main/resources/view/TextDisplay.fxml
> Fix bug where TextAreas were editable

- src/main/java/chopchop/logic/commands/ListIngredientCommand.java
- src/main/java/chopchop/logic/commands/ListRecipeCommand.java
- src/main/java/chopchop/ui/DisplayNavigator.java
> Make the list commands switch the gui pane

- src/main/java/chopchop/logic/commands/QuitCommand.java
- src/main/java/chopchop/logic/parser/CommandParser.java
- src/main/java/chopchop/util/Strings.java
> Add quit command

- src/main/java/chopchop/logic/parser/commands/AddCommandParser.java
> Add tag to parser

- src/main/java/chopchop/logic/autocomplete/AutoCompleter.java
- src/main/java/chopchop/ui/CommandBox.java
- src/test/java/chopchop/logic/autocomplete/AutoCompleterTest.java
- src/test/java/chopchop/testutil/TypicalIngredients.java
> Fix #133 — autocomplete for multi-word recipe and ingredient names

- src/main/java/chopchop/logic/parser/CommandArguments.java
- src/main/java/chopchop/logic/parser/CommandParser.java
- src/test/java/chopchop/logic/parser/CommandParserTest.java
> Fix #141 — allow escaping slashes in user input

- src/main/java/chopchop/ui/CommandBox.java
- src/main/java/chopchop/ui/MainWindow.java
Closes #152 
First keypress will not be displayed in the commandbox though :(
> CommandBox will be focused witth any keypress

- src/main/java/chopchop/commons/util/Strings.java
- src/main/java/chopchop/logic/autocomplete/AutoCompleter.java
- src/main/java/chopchop/logic/commands/FilterIngredientCommand.java
- src/main/java/chopchop/logic/commands/FilterRecipeCommand.java
- src/main/java/chopchop/logic/commands/FindIngredientCommand.java
- src/main/java/chopchop/logic/commands/FindRecipeCommand.java
- src/main/java/chopchop/logic/parser/ArgName.java
- src/main/java/chopchop/logic/parser/CommandParser.java
- src/main/java/chopchop/logic/parser/commands/EditCommandParser.java
- src/main/java/chopchop/model/attributes/units/Volume.java
- src/test/java/chopchop/logic/autocomplete/AutoCompleterTest.java
> Fix #129 — add autocomplete for edit, view, and filter

- src/main/java/chopchop/commons/util/StringView.java
- src/main/java/chopchop/logic/commands/AddIngredientCommand.java
- src/main/java/chopchop/logic/commands/AddRecipeCommand.java
- src/main/java/chopchop/logic/commands/EditRecipeCommand.java
- src/main/java/chopchop/logic/parser/CommandParser.java
- src/main/java/chopchop/logic/parser/ItemReference.java
- src/main/java/chopchop/logic/parser/commands/AddCommandParser.java
- src/main/java/chopchop/logic/parser/commands/EditCommandParser.java
- src/main/java/chopchop/logic/parser/commands/FindCommandParser.java
- src/main/java/chopchop/logic/parser/commands/ListCommandParser.java
- src/main/java/chopchop/logic/parser/commands/MakeCommandParser.java
- src/main/java/chopchop/logic/parser/commands/ViewCommandParser.java
- src/main/java/chopchop/model/attributes/Quantity.java
- src/main/java/chopchop/model/attributes/units/Count.java
- src/main/java/chopchop/model/attributes/units/Mass.java
- src/main/java/chopchop/model/attributes/units/Volume.java
- src/main/java/chopchop/model/ingredient/Ingredient.java
- src/main/java/chopchop/model/ingredient/IngredientReference.java
- src/main/java/chopchop/model/recipe/Recipe.java
- src/test/java/chopchop/logic/commands/AddIngredientCommandIntTest.java
- src/test/java/chopchop/logic/commands/AddIngredientCommandTest.java
- src/test/java/chopchop/logic/parser/CommandParserTest.java
- src/test/java/chopchop/logic/parser/ItemReferenceTest.java
- src/test/java/chopchop/model/attributes/QuantityTest.java
Closes #139 
Closes #156 
Closes #90
> Validate Ingredients and Propagate Errors

- src/main/java/chopchop/ui/DisplayController.java
- src/main/java/chopchop/ui/IngredientViewPanel.java
- src/main/java/chopchop/ui/RecipeViewPanel.java
> Fix #154 — specify that the list is empty because of no matches, not because no recipes/ingredients added

- src/main/java/chopchop/ui/RecipeDisplay.java
- src/main/resources/view/RecipeDisplay.fxml
- src/main/resources/view/Style.css
> Show tags in recipe view

- src/main/java/chopchop/logic/commands/AddIngredientCommand.java
- src/main/java/chopchop/model/attributes/units/Volume.java
- src/main/java/chopchop/model/ingredient/Ingredient.java
- src/main/java/chopchop/ui/IngredientCard.java
- src/main/java/chopchop/ui/IngredientViewPanel.java
- src/main/java/chopchop/ui/RecipeCard.java
- src/main/java/chopchop/ui/RecipeDisplay.java
- src/main/resources/view/IngredientCard.fxml
- src/main/resources/view/RecipeCard.fxml
- src/main/resources/view/RecipeDisplay.fxml
- src/main/resources/view/Style.css
- src/test/java/chopchop/logic/parser/CommandParserTest.java
- src/test/java/chopchop/model/attributes/QuantityTest.java
> Miscellaneous fixes

- src/main/java/chopchop/logic/commands/EditRecipeCommand.java
- src/test/java/chopchop/logic/commands/EditRecipeCommandTest.java
> Display sensible error messages when step indices are out of range for `edit recipe`

- src/main/java/chopchop/logic/parser/commands/AddCommandParser.java
- src/main/java/chopchop/logic/parser/commands/CommonParser.java
- src/main/java/chopchop/logic/parser/commands/DeleteCommandParser.java
- src/main/java/chopchop/logic/parser/commands/EditCommandParser.java
- src/test/java/chopchop/logic/parser/commands/AddCommandParserTest.java
- src/test/java/chopchop/logic/parser/commands/EditCommandParserTest.java
Fixes #241 
Fixes #240 
Fixes #237
> Forbid negative quantities at the parser level

- docs/UserGuide.md
- src/main/java/chopchop/logic/autocomplete/AutoCompleter.java
- src/main/java/chopchop/logic/commands/HelpCommand.java
- src/main/java/chopchop/logic/commands/MakeRecipeCommand.java
- src/main/java/chopchop/logic/commands/ViewRecipeCommand.java
- src/main/java/chopchop/logic/parser/commands/CommonParser.java
- src/main/java/chopchop/logic/parser/commands/EditCommandParser.java
- src/main/java/chopchop/logic/parser/commands/MakeCommandParser.java
- src/main/java/chopchop/logic/parser/commands/ViewCommandParser.java
- src/test/java/chopchop/logic/autocomplete/AutoCompleterTest.java
- src/test/java/chopchop/logic/commands/HelpCommandTest.java
- src/test/java/chopchop/logic/commands/MakeCommandTest.java
- src/test/java/chopchop/logic/commands/MakeRecipeCommandTest.java
- src/test/java/chopchop/logic/commands/ViewRecipeCommandTest.java
- src/test/java/chopchop/logic/parser/CommandParserTest.java
- src/test/java/chopchop/ui/CommandBoxTest.java
Now `make` and `view` need `make recipe` and `view recipe`.
Closes #215 
Closes #205
> Unify command targets

- src/main/java/chopchop/ui/DisplayController.java
- src/main/java/chopchop/ui/IngredientViewPanel.java
- src/main/java/chopchop/ui/MainWindow.java
- src/main/java/chopchop/ui/RecipeViewPanel.java
- src/main/java/chopchop/ui/RecommendationViewPanel.java
- src/main/resources/view/IngredientViewPanel.fxml
- src/main/resources/view/TextDisplay.fxml
> Fix #253, fix #251, adjust sizes to nice numbers

- src/main/java/chopchop/logic/commands/Command.java
> Improve error message when deleting from an empty list

- src/main/java/chopchop/logic/autocomplete/AutoCompleter.java
- src/test/java/chopchop/logic/autocomplete/AutoCompleterTest.java
- src/test/java/chopchop/logic/parser/CommandParserTest.java
> (#141) Fix autocompleter with names containing slashes

- README.md
- docs/UserGuide.md
> Update UG (2 of ?)

- src/main/java/chopchop/logic/commands/StatsIngredientUsedCommand.java
- src/main/java/chopchop/logic/commands/StatsRecipeMadeCommand.java
- src/main/java/chopchop/model/usage/Usage.java
> (#273 + #272) Fix date-related oversights for stats commands

- docs/UserGuide.md
> Add section 4.7

- src/main/java/chopchop/logic/autocomplete/AutoCompleter.java
> (#285) Fix autocompleter edge cases

- src/main/java/chopchop/logic/commands/FilterIngredientCommand.java
- src/main/java/chopchop/logic/commands/FilterRecipeCommand.java
- src/main/java/chopchop/logic/parser/commands/FilterCommandParser.java
- src/main/java/chopchop/model/attributes/IngredientsContainsKeywordsPredicate.java
- src/main/java/chopchop/model/attributes/NameContainsKeywordsFilterPredicate.java
- src/test/java/chopchop/logic/commands/FilterIngredientCommandTest.java
- src/test/java/chopchop/logic/commands/FilterRecipeCommandTest.java
- src/test/java/chopchop/logic/parser/CommandParserTest.java
- src/test/java/chopchop/model/attributes/NameContainsKeywordsFilterPredicateTest.java
> Add /name field in filter search

- README.md
- docs/index.md
- src/main/java/chopchop/commons/util/BulkEditableObservableList.java
- src/main/java/chopchop/commons/util/Result.java
- src/main/java/chopchop/logic/commands/MakeRecipeCommand.java
- src/main/java/chopchop/model/EntryBook.java
- src/main/java/chopchop/model/Model.java
- src/main/java/chopchop/model/ModelManager.java
- src/main/java/chopchop/model/UniqueEntryList.java
- src/main/java/chopchop/model/util/SampleDataUtil.java
- src/main/java/chopchop/ui/RecipeDisplay.java
- src/main/resources/stylesheets/Style.css
- src/main/resources/view/IngredientCard.fxml
- src/test/java/chopchop/model/ModelStub.java
- src/test/java/chopchop/testutil/StubbedModel.java
> Pre-1.4 Release Cleanup

- docs/UserGuide.md
> Update UG (8 of ?)

- docs/AboutUs.md
- docs/DeveloperGuide.md
- docs/team/fall9x.md
> Update DG (6 of ?)
